FROM python:3.11-slim

ARG MLFLOW_TRACKING_URI_DOCKER
ARG MINIO_ACCESS_KEY
ARG MINIO_SECRET_KEY
ARG MINIO_HOST
ARG MINIO_PORT
ARG MINIO_BUCKET
ARG REDIS_URL
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG MLFLOW_S3_ENDPOINT_URL

ENV MLFLOW_TRACKING_URI_DOCKER=$MLFLOW_TRACKING_URI_DOCKER
ENV MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
ENV MINIO_SECRET_KEY=$MINIO_SECRET_KEY
ENV MINIO_HOST=$MINIO_HOST
ENV MINIO_PORT=$MINIO_PORT
ENV MINIO_BUCKET=$MINIO_BUCKET
ENV REDIS_URL=$REDIS_URL
ENV AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY
ENV MLFLOW_S3_ENDPOINT_URL=MLFLOW_S3_ENDPOINT_URL

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --upgrade pip

RUN pip install poetry

RUN poetry config virtualenvs.create false

WORKDIR /app
COPY pyproject.toml poetry.lock* /app/


RUN poetry install --no-root
COPY . .

CMD ["uvicorn", "src.recommender_system.presentation.api:app", "--host", "0.0.0.0", "--port", "8000"]

